import type { Metadata } from "next";
import { Header } from "@/components/Header";
import "./globals.css";
import Breadcrumb from "@/components/Breadcrumb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'antialiased'}
      >       
        <Header /> 
        <Breadcrumb separator=" > " containerClasses="breadcrumb" listClasses="breadcrumb-item" activeClasses="active" />
        {children}
      </body>
    </html>
  );
}
